POST localhost:9501/api/users/signup
Content-Type: application/json

{
    "email": "test167@test.com",
    "password": "test2"
}
> {%
  client.global.set('token', response.headers.valuesOf("Token")[0]);
%}
###

POST localhost:9501/api/users/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}
> {%
  client.global.set('token', response.headers.valuesOf("Token")[0]);
%}
###

POST localhost:9501/api/users/signin
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}
> {%
  client.global.set('token', response.headers.valuesOf("Token")[0]);
%}
###

POST localhost:9501/api/users/signout
Content-Type: application/json
Token: {{ token }}

> {%
  client.global.set('token', response.headers.valuesOf("Token")[0]);
%}
###

GET localhost:9501/api/users/currentuser
Content-Type: application/json
Token: {{ token }}
###

#==========================================================Testing======================================================
#### Authorization by token, part 1. Retrieve and save token.
#POST https://httpbin.org/post
#Content-Type: application/json
#
#{
#    "token": "my-secret-token"
#}
#
#> {% client.global.set("auth_token", response.body.json.token); %}
#
#### Authorization by token, part 2. Use token to authorize.
#GET https://httpbin.org/headers
#Authorization: Bearer {{auth_token}}
#
####

# 1.
POST localhost:9501/api/users/signin
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}
> {%
  client.global.set('token', response.headers.valuesOf("Token")[0]);
%}
###

# 2.
POST localhost:9502/api/tickets/create
Content-Type: application/json
Token: {{ token }}

{
    "title": "Ticket 1",
    "price": 123
}
###

# 3.
POST localhost:9503/api/orders/create
Content-Type: application/json
Token: {{ token }}

{
    "ticket_id": 4
}
###

# 4.
POST localhost:9505/api/payments
Content-Type: application/json
Token: {{ token }}

{
    "token": "tok_visa",
    "order_id": 1
}
###